config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :albums do
  	resources :reviews
  end
  root 'albums#index'


 # mount ActionCable.server => '/cable'
end

app/models/album.rb
class Album < ApplicationRecord
	has_many :reviews
	belongs_to :user
	validates :title, presence: true
	validates :cover, presence: true
	validates :year, presence: true
	validates :artist, presence: true
	
	has_attached_file :cover, styles: { normal: "400x400#", medium: "400x400>", thumb: "100x100>" }, default_url: "/images/:style/missing.png", default_style: :normal
    validates_attachment_content_type :cover, content_type: /\Aimage\/.*\z/

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :user 
	belongs_to :album
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :albums
  has_many :reviews
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :new, :update, :destroy]

  def index
    @albums = Album.all
    if params[:search].nil?
      @albums = Album.all.order(year: :desc).order(title: :asc).paginate(:page => params[:page], :per_page => 24)
    else
      @albums = @albums.where("albums.title || albums.year || albums.artist LIKE ?", "%#{params[:search]}%").order(year: :desc).order(title: :asc).paginate(:page => params[:page], :per_page => 24)
    end
  end

  def show
    if @album.reviews.blank?
      @average_review = 0
    else
      @average_review = @album.reviews.average(:rating).round(2)
    end
    @review = Review.new(album: @album)
    @reviews = @album.reviews.all.order(created_at: :desc)
  end

  def new
    @album = Album.new
  end

  def edit

  end

  def create
    @album = current_user.albums.build(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, notice: 'Album was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_album
      @album = Album.find(params[:id])
    end

    def album_params
      params.require(:album).permit(:title, :artist, :year, :cover)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :set_album
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]



  def new
    @review = Review.new
  end

  def show
    
  end

  def create
    @review = Review.new(review_params)
    @review.album_id=@album.id
    @review.user_id=current_user.id
    if @review.save
        ActionCable.server.broadcast 'reviews' ,
        render( partial: 'reviews/review', object: @review )
    else
        render 'new'
    end
    redirect_to album_path(@album)
  end

  def edit

  end

  def update
    if @review.update(review_params)
      redirect_to album_path(@album)
    else
      render 'edit'
    end
  end

  def destroy
    @review.destroy
    if @review.destroy
      redirect_to album_path(@album)
    end
  end

  private

    def set_review
      @review = Review.find(params[:id])
    end
    
    def set_album 
      @album = Album.find(params[:album_id])
    end 

    def review_params
      params.require(:review).permit(:comment, :user_id, :album_id, :rating)
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
  return '' if resource.errors.empty?

  messages = resource.errors.full_messages.map { |msg| content_tag(:p, msg) }.join
  sentence = I18n.t('errors.messages.not_saved',
  count: resource.errors.count,
  resource: resource.class.model_name.human.downcase)

  # for Bootstrap 3 pay attention to the classes in the "div"

  html = <<-HTML
  <div class="alert alert-danger alert-dismissable"> 
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  #{messages}</div>
  HTML
  html.html_safe
 end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/albums/_form.html.erb
<%= simple_form_for @album do |f| %>
 <div class="form-group">
  <%= f.input :title, class: 'form-control' %>
 </div>
 <div class="form-group">
 	<%= f.input :artist, class: 'form-control' %>
 </div>
 <div class="form-group">
  <%= f.input :year, class: 'form-control'  %>
 </div>
 <label for="cover">Cover Image</label>
  <%= f.file_field :cover, class: 'white' %> 
 <br /><br />
  <%= f.button :submit, class: 'btn btn-grey' %>
<% end %>

app/views/albums/edit.html.erb
<div class="row">
	<div class="col-md-4 col-md-push-4 col-sm-6 col-sm-push-3 col-xs-10 col-xs-push-1 top">
		<h2>Edit Album</h2>
		<br />
		<%= render 'form', album: @album %>
		<br />
	</div>
</div>

app/views/albums/index.html.erb
<div class="row">
      <% @albums.each do |album| %>
      <a href="/albums/<%= album.id %>">
        <div class="col-lg-3 col-sm-4 col-xs-6 index_container">
          <% if album.cover.blank? %>
            <p><%= album.title %></p>
            <p><%= album.artist %></p>
            <p><%= album.year %></p>
            <%= link_to "Show", album_path(album), class: 'grey' %>
            <%= link_to "Edit", edit_album_path(album), class: 'grey' %>
            <%= link_to "Destroy", album_path(album), method: :delete, data: {confirm: "Are you sure?"}, class: 'grey' %>
          <% else %> 
          <!-- <div class="index_image" style="background-image: url('<%= album.cover %>')"></div> -->
           <%= image_tag album.cover, class: 'index_image medium' %> 
          <% end %>
        </div>
        </a>
      <% end %>
      <div class="col-xs-12 paginate_container">
        <%= will_paginate @albums, class: 'apple_pagination' %>
      </div>
  <br>
</div>

app/views/albums/new.html.erb
<div class="row">
	<div class="col-md-4 col-md-push-4 col-sm-6 col-sm-push-3 col-xs-10 col-xs-push-1 top">
		<h2>New Album</h2>
		<br />
		<%= render 'form', album: @album %>
	</div>
</div>

app/views/albums/show.html.erb
<% provide(:title, "| #{@album.title}") %>

<div class="row">
	<div class="col-xs-10 col-md-6 col-md-push-3 col-xs-push-1 top bottom">
		<%= image_tag @album.cover, class: 'show_image' %>
		<h2><%= @album.title %></h2>
		<h4><%= @album.artist %></h4>
		<h5><%= @album.year %></h5>
		<% if user_signed_in? %>
			<% if @album.user_id == current_user.id %> 
				<%= link_to 'Edit', edit_album_path(@album), class: 'grey' %> 
				| <%= link_to 'Delete', album_path, method: :delete, data: {confirm: "Are you sure?"}, class: 'grey' %>
				<br /><br />
			<% end %> 
		<% end %>
		<p class="white">Average Review<div class="average-review-rating" data-score=<%= @average_review %>></div></p>
		<br />
			<h4>Write a Review</h4>	
			<%= form_for [@album, @review], remote: true do |r| %>
				<div class="form-group">
					<div id="rating-form">
						<label>Rating</label>
					</div>	
				</div>
				<div class="form-group">
					<%= r.text_area :comment, class: 'form-control', placeholder: "Write a comment" %>
				</div>
				<% if user_signed_in? %>
					<div class="form-group">
						<%= r.submit "Create", class: 'btn btn-grey' %>
					</div>
				<% else %>
					<%= link_to "Create", new_album_review_path(@album), class: "btn btn-grey" %> 
					<br />
				<% end %> 
			<% end %> 
		<br /><br />
		<h4>Reviews</h4>
		<% if @album.reviews.empty? %> 
			<p class="grey"><i>There are no reviews for this album yet.</i></p> 
		<% else %> 
			<div id="reviews"> <!--- ActionCable -->
				<% @reviews.each do |r| %>
					<div>
						<div class="review-rating" data-number="<%= r.rating %>">
						</div>
						<p class="white"><%= r.comment %></p>
						<p class="grey"><i>posted <%= time_ago_in_words(r.created_at) %> ago</i></p> 
						<% if user_signed_in? %>
							<% if current_user.id == r.user_id %> 
								<%= link_to 'Edit', edit_album_review_path(@album, r.id), class: 'grey' %> |
								<%= link_to 'Delete', album_review_path(@album, r.id), method: :delete, data: {confirm: "Are you sure?"}, class: 'grey' %>
								<br /><br />
							<% end %> 
						<% else %> 
							<br />
						<% end %>
					</div>
				<% end %>
			<div id="reviews"> <!--- ActionCable -->
		<% end %> 
	</div>
</div>



<script> 
$('.review-rating').raty({
	readOnly: true,
	score: function() {
		return $(this).attr('data-number');
	},
	path: '/assets/'
});

$('#rating-form').raty({
	path: '/assets/',
	scoreName: 'review[rating]'
});

$('.average-review-rating').raty({
	readOnly: true,
	path: '/assets/',
	score: function() {
		return $(this).attr('data-score')
	}
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlbumReview <%= yield(:title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= favicon_link_tag %> 
    <%= action_cable_meta_tag %>

    <meta property="og:title" content="Album Review <%= yield(:title) %>">
    <meta property="og:description" content="Share reviews of your favorite albums with family and friends">
    <meta property="og:image" content="http://www.seaboltdesign.com/record.jpg">
    <meta property="og:url" content="http://www.albumreview.herokuapp.com">
    <meta name="twitter:card" content="summary_large_image">
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          <a class="navbar-brand" href="/"><span style="color: white">Album</span><span class='light'>Review</span></a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
              <li><%= link_to "Home", albums_path %></li>
              <li><%= link_to "Add Album", new_album_path %> </li>
            <% if user_signed_in? %>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
            <% else %> 
              <li><%= link_to "Log in", new_user_session_path %></li>
            <% end %> 
          </ul>
          <form class="navbar-form navbar-left">
            <div class="form-group">
            <%= text_field_tag :search, params[:search], placeholder: 'Search', class: "form-control form-control nav_search" %>
            </div>
            <%= submit_tag "Search", class: "btn btn-nav" %>
          </form>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <div class="navbar_placeholder">
    </div>
  	<div class="container-fluid">
    	<%= yield %>
    </div>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= simple_form_for([@album, @album.reviews.build]) do |f| %>
	<%= f.error_notification %>
		<div id="rating-form">
			<label>Rating</label>
		</div>	
	  	<div class="form-inputs">
	  		<%= f.input :comment, as: :text, :input_html => { class: 'test', :rows => 10 } %>
	  	</div>
	  	<br />
	 	<div class="form-actions">
	    	<%= f.button :submit, class: 'btn btn-grey'  %>
	  	</div>
	<% end %>

	<script>
	$('#rating-form').raty({
		path: '/assets/',
		scoreName: 'review[rating]'
	});
	</script>

app/views/reviews/_review.html.erb
<div>
	<div class="review-rating" data-number="<%= @review.rating %>">
	</div>
	<p class="white"><%= @review.comment %></p>
	<p class="grey"><i>posted <%= time_ago_in_words(@review.created_at) %> ago</i></p> 
	<% if user_signed_in? %>
		<% if current_user.id == @review.user_id %> 
			<%= link_to 'Edit', edit_album_review_path(@album, @review.id), class: 'grey' %> |
			<%= link_to 'Delete', album_review_path(@album, @review.id), method: :delete, data: {confirm: "Are you sure?"}, class: 'grey' %>
			<br /><br />
		<% end %> 
	<% else %> 
		<br />
	<% end %>
</div>


<script> 
	$('.review-rating').raty({
		readOnly: true,
		score: function() {
			return $(this).attr('data-number');
		},
		path: '/assets/'
	});
</script>

app/views/reviews/edit.html.erb
<div class="row">
	<div class="col-xs-10 col-xs-push-1 col-sm-6 col-sm-push-3 top">
		<h2>Editing Review</h2>
		<%= simple_form_for([@album, @review]) do |f| %>
			<%= f.error_notification %>
		<div id="rating-form">
			<label>Rating</label>
		</div>	
	  	<div class="form-inputs">
	  		<%= f.input :comment, as: :text, :input_html => { class: 'test', :rows => 10 } %>
	  	</div>
	  	<br />
	 	<div class="form-actions">
	    	<%= f.button :submit, class: 'btn btn-grey' %>
	  	</div>
	<% end %>

	<script>
	$('#rating-form').raty({
		path: '/assets/',
		scoreName: 'review[rating]'
	});
	</script>
	</div>
</div>

app/views/reviews/new.html.erb
<div class="row">
	<div class="col-xs-10 col-xs-push-1 col-sm-6 col-sm-push-3 top">
		<h2>New Review</h2>
		<%= render 'form', review: @review %>
	</div>
</div>

app/views/reviews/show.html.erb
<% provide(:title, "| #{@album.title}") %>

<div class="row">
  <div class="col-xs-10 col-md-6 col-md-push-3 col-xs-push-1 top bottom">
    <%= image_tag @album.cover, class: 'show_image' %>
    <h2><%= @album.title %></h2>
    <h4><%= @album.artist %></h4>
    <h5><%= @album.year %></h5>
    <br />
    <p class="white">Review</p><div class="review-rating" data-number="<%= @review.rating %>"></div>
    <% if user_signed_in? %>
      <% if @album.user_id == current_user.id %> 
        <%= link_to 'Edit', edit_album_review_path(@album, @review), class: 'grey' %> 
        | <%= link_to 'Delete', album_review_path, method: :delete, data: {confirm: "Are you sure?"}, class: 'grey' %>
        <br />
      <% end %> 
    <% end %>
    <br />
    <p class="white"><%= @review.comment %></p> 
    <br />
  </div>
</div>

<script> 
$('.review-rating').raty({
  readOnly: true,
  score: function() {
    return $(this).attr('data-number');
  },
  path: '/assets/'
});

$('#rating-form').raty({
  path: '/assets/',
  scoreName: 'review[rating]'
});

$('.average-review-rating').raty({
  readOnly: true,
  path: '/assets/',
  score: function() {
    return $(this).attr('data-score')
  }
});
</script>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name), class: 'grey' %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name), class: 'grey' %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name), class: 'grey' %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name), class: 'grey' %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name), class: 'grey' %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), class: 'grey' %><br />
  <% end -%>
<% end -%>